version: '3.8'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mealmate
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: mealmate
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - .:/app

volumes:
  mysql_data:
